### ISSUE TITLE
Doesn't work currently?

### ISSUE THREAD

**Issue by phortx** [straight-shoota/crinja#1]
I've added crinja to my `shard.yml`,  ran `crystal deps` and tried to build the app with a `require "crinja"`,  but it just produced errors like:

```
in lib/crinja/src/crinja/runtime/py_tuple.cr:1: while requiring "../value": can't find file '../value' relative to '/home/phortx/workspaces/benny/tesseract/lib/crinja/src/crinja/runtime'

require "../value"
```

and 

```
in lib/crinja/src/crinja/lib/function/cycler.cr:9: undefined method 'getattr'

  getattr :next, :rewind, :reset, :current
  ^~~~~~~
```

**Comment by straight-shoota** [comment]
Hey @phortx,
Crinja should be mostly operational as is proven by passing the quite extensive [test suite](https://travis-ci.org/straight-shoota/crinja).

The first error is indeed a mistake in Crinja, though I am not sure why the compiler did not complain about this, neither on my PC nor the test suite on travis-ci. It looks like a compiler bug, so I've opened issue [crystal-lang/crystal#4742](https://github.com/crystal-lang/crystal/issues/4742) to track this. The Crinja code should be fixed now.

What version of Crystal are you using (shell `crystal --version`)? Crinja depends on the current release `Crystal 0.23.1` (or newer). The second error might be related to an issue in previous versions of Crystal.

**Comment by phortx** [comment]
Wow, thanks for the fast response and the fix!

My crystal version is `Crystal 0.23.0 (2017-07-13) LLVM 4.0.1`, so I'll wait for 0.23.1 to be in the Manjaro Repos and will try again.

**Comment by straight-shoota** [comment]
All right, then it's the macro lookup bug in `0.23.0` ([crystal-lang/crystal#4639](https://github.com/crystal-lang/crystal/issues/4639).
It should be working under `0.23.0` if the class-scope calls to `getattr` are explicitly prefixed as `PyObject.getattr`. Though I don't plan to provide a patch with this because `0.23.1` is already out as a bugfix release to address this issue.
