### ISSUE TITLE
Calling to crystal methods

### ISSUE THREAD

**Issue by crisward** [straight-shoota/crinja#2]
I've read your docs and looked through the examples and I couldn't find an example of calling some method from the template. I'm using slang at the moment, which is obviously compile time. I'd like runtime templating if possible, but I can't work out how to do something.

We have a method called menu. It takes an int32 which is uses to look some stuff up in a database, then generate some html, then returns that html.

eg
```html
<ul>
  menu(1)
</ul>
```
would produce
```html
<ul>
  <li class="active"><a href="/">Home</a></li>
  <li><a href="/about/">About</a></li>
  <li><a href="/products/">Products</a></li>
</ul>
```

How would I make my menu method work from crinja? I'm guessing I have to wrap the method in something, can't get my head around what Functions and Tags are in Crinja, not familiar with Jinja.

**Comment by crisward** [comment]
Ok, I think I've sort of worked this out.... Any feedback would be welcome.

```crystal
module Crinmess
  extend self

  get "/" do |env|
    path = env.request.path
    begin
      template = crinja.get_template("index.html")
      vars = {
        "sample_data" => ["one", "two", "three"],
      }
      template.render(vars)
    rescue e : Crinja::TemplateNotFoundError
      puts e.message
      env.response.respond_with_error "File Not Found", 404
    end
  end
  
  # this create a custom function callable from the template
  crinja.functions << Crinja.function({:id => 0}, :menu) do
    id = arguments[:id].to_i
    Somelib.menu(id) #this will return string to template
  end

  Kemal.run
end
```

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Crinja</title>
  </head>
  <body>
    <!-- the safe filter allows html to be output unescaped -->
    <ul>{{ menu(1) | safe}}</ul>
  </body>
</html>

```

**Comment by crisward** [comment]
Just wanted to let you know that I've got this working with our content management system and I couldn't be happier. 

We have been using slang as we all like the short hand html. However the runtime templates are going to save us a ton of time on recompiling so I've added crinja as an option. Even though this is run time it seems just as quick.

Thanks for the excellent work. Will feedback any issues if we find them.

**Comment by straight-shoota** [comment]
Hey @crisward, I was on vacation and couldn't answer right away. But I would have suggested the solution you've found by yourself. I'll look into further improving the documentation.

It's great to see Crinja put to use! I'm happy for any feedback. At the current stage, Crinja just needs more users and real use cases to be improved further.

**Comment by crisward** [comment]
If it helps we're trying crinja on our front page, all other pages on the site are using slang. 
https://www.duodesign.co.uk seems as performant as other pages.

There are a couple of issues I've found with the limited types, but I may be able to get around them. 

The other issue I've had is the jump in compile time, from 14seconds to 18+ seconds. We don't have to recompile as much as the templates are run time, so this extra time is probably worth it. I've no idea what increase compile times beyond lines of code, but thought it was worth mentioning.
