### ISSUE TITLE
Embedding macros in template files

### ISSUE THREAD

**Issue by lebogan** [straight-shoota/crinja#23]
First off - this is seriously awesome! I want to embed the following Crystal macro in a template file but crinja keeps giving me errors. The macro:
```
VERSION    = {{ `shards version #{__DIR__}`.chomp.stringify }}
```
The error:
unhandled exception: Not implemented expression value ```

Looks like a lot of escaping is needed. Suggestions on possibly doing this?

Thank you.

**Comment by straight-shoota** [comment]
Thank you! I'm glad that it helps you.

There are two options for this:

* print the curly braces as Crinja expressions: `{{ "{{" }}` (you could put the entire macro expression in a Crinja string, but that would potentially require some escaping)
* wrap the section in a `{% raw %}` tag.

This is also explained in the Jinjia documentation: http://jinja.pocoo.org/docs/2.10/templates/#escaping

**Comment by lebogan** [comment]
No idea how I missed that in the docs! Thanks again.
