### ISSUE TITLE
crystal 0.29.0 support

### ISSUE THREAD

**Issue by lebogan** [straight-shoota/crinja#24]
This error shows up using crinja (not with crystal 0.28.0). I can't find what broke by looking through the changelog.
```
Error in src/quikweb.cr:24: while requiring "crinja"
.
in macro 'filter' /vagrant/Projects/crystal/quikweb/lib/crinja/src/runtime/callable.cr:69, line 1:
.
.
expanding macro
in lib/crinja/src/lib/filter/number.cr:24:no overload matches 'String#to_f?' with type Int32
Overloads are:
 - String#to_f?(whitespace : Bool = true, strict : Bool = true)

        result = raw.to_f?(arguments["base"].to_i).try &.to_i
```

**Comment by straight-shoota** [comment]
This was a bug in crinja, `String#to_f` never accepted an `Int` argument but this didn't error before. In 0.29.0 the first argument to that method has gained a `Bool` type restriction, that's what makes this error apparent.

Support for 0.29.0 is already available in master, but I'll also cut a new release.

**Comment by lebogan** [comment]
Thanks. Using `branch: master` in my `shard.yml` fixes it for now.
