### ISSUE TITLE
HTML rendered literally in docs

### ISSUE THREAD

**Issue by yujiri8** [straight-shoota/crinja#35]
From https://straight-shoota.github.io/crinja/api/latest/#configuration:

![20200913_16h41m25s_grim](https://user-images.githubusercontent.com/16864184/93028157-faa74600-f5df-11ea-9cc3-c1fb064e00b1.png)

**Comment by straight-shoota** [comment]
Yeah, that's a a limitation of Crystal's doc generator. There's nothing to be done to fix this except for waiting for better Markdown support in the generator. A properly rendered page is available at https://straight-shoota.github.io/crinja/
