### ISSUE TITLE
Json parse in template

### ISSUE THREAD

**Issue by ozergul** [straight-shoota/crinja#8]
Hello
I send current user to index.html but can parse it. What is the correct way?

``` crystal
get "/" do |env|
  user = User.find(2).as(User)
  user.to_json unless user.nil?
  template = cri.get_template("index.html")
  template.render({"user" => user})
end
```
`{{user}}` writes this:

> {"id":2,"username":"a","email":"a","password":"s","role":"user","created_at":"2018-05-18T15:09:27+0300","updated_at":"2018-05-18T15:09:27+0300"}

Cant parse it with `{{user.username}}` or `{{user["username"]}}`

Maybe simple question, but I am very new to Crystal :)  
Thanks in advance.

**Comment by ozergul** [comment]
Solved it with template-side function.

```
cri.functions << Crinja.function({:str => ""}, :Parse) do
  JSON.parse(arguments[:str].to_s)
end
```
Usage:
`{{Parse(user)["username"]}}`

Maybe there is easy way but for now it works.

**Comment by straight-shoota** [comment]
@ozergul When you assign an instance of `User` to the `user` variable in Crinja, it should be accessible as a `User` object in a Crinja template. But Crinja doesn't know the Crystal API of this class, so you need to add methods like `#getattr` or `#getitem` to the class in order for Crinja to be able to access it's properties. See https://github.com/straight-shoota/crinja/blob/master/playground/objects.md for an example.

You should also be able to pass the object converted to JSON as `JSON::Any`, but it's typically better to use the class directly and provide accessors for Crinja.

**Comment by ozergul** [comment]
I found interesting solution and maybe it's bad but it works pretty good :) (I am pretty new to Crystal)

``` crystal
def parsed(object)
  JSON.parse(object.json) unless object.nil?
end
```

usage:

```crystal
user = Repo.get_by(User, id: id)
...
template.render({
      "user" => parsed(user)
})
```

**Comment by straight-shoota** [comment]
Yes, that's what I mentioned in my last sentence. This convertes your object of type `User` to a `JSON::Any` and that can be used by Crinja to access it's properties.

This works and if it's good enough for your use case, that's fine.
Having direct access to the object and it's properties using `#getattr` would be cleaner and more performant, though.
